export const messages = {
    DB_CONNECTED : "Database has been connected successfully.",
    SERVER_FAILED_TO_START : "Failed to start server",
    SERVER_STARTED : "Server have been successfully started",
    PHONE_INUSE : "The phone number you provided has been taken.",
    SERVER_ERROR : "Sorry an internal server error occured, please try again.",
    ACCOUNT_CREATED : "Account has been successfully created.",
    UNAUTHORIZED : "Unauthorized request.",
    INVALID_OTP : "The OTP you provided is invalid.",
    OTP_VERIFIED : "OTP has successfully verified.",
    PHONE_NOT_VERIFIED : "Phone number has been validated.",
    DETAILS_UPDATED : "Account details have been successfully updated.",
    NOT_FOUND : "Resource not found",
    OTP_RESENT : "Otp has been successfully resent.",
    PIN_CREATED : "Your pin has been successfully created.",
    LOGIN_SUCCESSFUL : "Login was successful.",
    ID_ALREADY_VERIFIED : "You have already verified your Id.",
    FAILED_TO_VERIFY_ID : "Failed to verify your id, please check the information you provided",
    ID_VERIFIED : "Id has been successfully verified.",
    ID_REQUIRED : "Id front and back are required.",
    USER_NOT_FOUND : "User not found.",
    USER_FOUND : "User found.",
};